language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_install:
 - cp tests/TestConfiguration.php.travis tests/TestConfiguration.php
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install --dev

before_script:
  - pyrus install -o pear.phpunit.de/PHPUnit
  - phpenv rehash

script:
  - phpunit -c tests/phpunit.xml.dist

notifications:
  irc: "irc.freenode.org#zftalk.2"
